version: "3"

services:
  postgres:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "ecto_diff_migrate_test"
    ports:
      - 5432:5432
